### ISSUE TITLE
SSL Certifcate error

### ISSUE THREAD

**Issue by Orchid420** [inquirim/inquisitor#5]
I get this issue:

SLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

**Comment by econdb** [comment]
Hi @Orchid420 

could you add in a comment the commands the program is executing?

The website certificate hasn't expired so I would be interested to see the URL you are requesting.

Regards

**Comment by Orchid420** [comment]
Hey, 

I am running the basic example:

import inquisitor
qb = inquisitor.Inquisitor()

qb.verify=False
## List sources 
qb.sources()

### List datasets
qb.datasets(source='EU')

### Obtain series data
qb.series(dataset='EI_BSCO_M')

Usually I run that before making a request:
import requests
session = requests.Session()
session.verify = False

But I am not sure how to do it with your command.

**Comment by econdb** [comment]
that's interesting, it works fine on my side. 

Requesting data from the API is rather simple, it can be done with a `pandas` function. You would need to define what tickers you are interested in and then call the /api/series/ endpoint easily.
```
import pandas as pd
df = pd.read_csv(                    
	'https://www.econdb.com/api/series/CPIUS/?format=csv',                    
	index_col='Date', parse_dates=['Date'])
```

**Comment by Orchid420** [comment]
import requests
query = 'united states'
results = requests.get('https://www.econdb.com/api/series/?search=%s&format=json&expand=meta'% query,verify=False).json()['results']

Then I do the above command to get the list but I get only 10 results. I tried for both the US and Europe so I don't understand why I don't see more than 10 results. 

For example the US:

United States - Consumer price index
United States - Unemployment
United States - Real gross fixed capital formation
United States - Real public consumption
United States - Retail trade
United States - Industrial production
United States - Real gross domestic product
United States - Consumer confidence index
United States - Producer price index
United States - Government debt

**Comment by econdb** [comment]
you can jump to the following page of the results

https://www.econdb.com/api/series/?search=%s&format=json&expand=meta&page=%d

**Comment by Orchid420** [comment]
import requests
query = 'united states'

results = requests.get('https://www.econdb.com/api/series/?search=%s&format=json&expand=meta&page=%d'% query,verify=False).json()['results']

Error I get: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\BORIS~1.MIK\AppData\Local\Temp/ipykernel_62964/3513940416.py in <module>
      2 query = 'united states'
      3 
----> 4 results = requests.get('https://www.econdb.com/api/series/?search=%s&format=json&expand=meta&page=%d'% query,verify=False).json()['results']

TypeError: not enough arguments for format string

**Comment by econdb** [comment]
```
for i in range(1, 5):
    requests.get('https://www.econdb.com/api/series/?search=%s&format=json&expand=meta&page=%d' % (query, i), verify=False).json()['results']
```

the page argument needs to be populated, check the example
